/*
 * This file is generated by jOOQ.
 */
package jooq.entities.routines;


import javax.annotation.Generated;

import jooq.entities.Public;

import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1435421998;

    /**
     * Create a new routine call instance
     */
    public Test() {
        super("test", Public.PUBLIC);
    }
}
