/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postback;

import java.io.PrintWriter;
import javax.persistence.criteria.CriteriaBuilder;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;

import entities.User;
import org.apache.commons.lang3.StringUtils;
import utility.PostBackController;

/**
 * @author sukhvir
 */
//todo: this is not secure have to fix it
@WebServlet(urlPatterns = "/resetPasswordPost")
public class ResetPasswordPost extends PostBackController {

    // reset password of the user by proving the username, password and and a temp token. if the temp token present in the
    // the httpSession matches it then the password is changed.
    @Override
    public void process(HttpServletRequest req, HttpServletResponse resp, Session session, HttpSession httpSession, PrintWriter out) throws Exception {
        String username = req.getParameter("username");
        String password = req.getParameter("password");

        if (StringUtils.isNoneBlank(username, password)) {

            CriteriaBuilder builder = session.getCriteriaBuilder();


            User user = (User) session.createCriteria(User.class)
                    .add(Restrictions.eq("username", username))
                    .list()
                    .get(0);
        } else {

        }


       /* user.setPassword(password);
        user.setUsed(true);

        session.update(user);

        String body = "this is an autogenerated mail. Please don't reply or send mail to this address. Your password was changed on " + new Date();
        Utils.sendMail(user.getEmail(), "Password changed", body);

        resp.sendRedirect("login");*/
    }

}
