/*
 * This file is generated by jOOQ.
 */
package jooq.entities;


import jooq.entities.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.12"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADMIN_PKEY = Indexes0.ADMIN_PKEY;
    public static final Index ATTENDANCE_PKEY = Indexes0.ATTENDANCE_PKEY;
    public static final Index CLASS_ROOM_NAME = Indexes0.CLASS_ROOM_NAME;
    public static final Index CLASS_ROOM_NAME_INDEX = Indexes0.CLASS_ROOM_NAME_INDEX;
    public static final Index CLASS_ROOM_PKEY = Indexes0.CLASS_ROOM_PKEY;
    public static final Index CLASS_TEACHER_CLASS_ROOM_LINK_PKEY = Indexes0.CLASS_TEACHER_CLASS_ROOM_LINK_PKEY;
    public static final Index COURSE_NAME_INDEX = Indexes0.COURSE_NAME_INDEX;
    public static final Index COURSE_PKEY = Indexes0.COURSE_PKEY;
    public static final Index UNIQUE_COURSE_NAME = Indexes0.UNIQUE_COURSE_NAME;
    public static final Index DEPARTMENT_NAME_INDEX = Indexes0.DEPARTMENT_NAME_INDEX;
    public static final Index DEPARTMENT_PKEY = Indexes0.DEPARTMENT_PKEY;
    public static final Index DEPARTMENT_UNIQUE_NAME = Indexes0.DEPARTMENT_UNIQUE_NAME;
    public static final Index LECTURE_PKEY = Indexes0.LECTURE_PKEY;
    public static final Index STUDENT_NAME_INDEX = Indexes0.STUDENT_NAME_INDEX;
    public static final Index STUDENT_PKEY = Indexes0.STUDENT_PKEY;
    public static final Index STUDENT_SUBJECT_LINK_PKEY = Indexes0.STUDENT_SUBJECT_LINK_PKEY;
    public static final Index SUBJECT_PKEY = Indexes0.SUBJECT_PKEY;
    public static final Index SUBJECT_CLASS_LINK_PKEY = Indexes0.SUBJECT_CLASS_LINK_PKEY;
    public static final Index TCS_CLASS_ROOM_INDEX = Indexes0.TCS_CLASS_ROOM_INDEX;
    public static final Index TCS_PKEY = Indexes0.TCS_PKEY;
    public static final Index TCS_SUBJECT_INDEX = Indexes0.TCS_SUBJECT_INDEX;
    public static final Index TCS_TEACHER_INDEX = Indexes0.TCS_TEACHER_INDEX;
    public static final Index TEACHER_NAME_INDEX = Indexes0.TEACHER_NAME_INDEX;
    public static final Index TEACHER_PKEY = Indexes0.TEACHER_PKEY;
    public static final Index TEACHER_DEPARTMENT_LINK_PKEY = Indexes0.TEACHER_DEPARTMENT_LINK_PKEY;
    public static final Index UNIQUE_USER_EMAIL = Indexes0.UNIQUE_USER_EMAIL;
    public static final Index UNIQUE_USER_USERNAME = Indexes0.UNIQUE_USER_USERNAME;
    public static final Index UNIQUE_USER_USERNAME_EMAIL = Indexes0.UNIQUE_USER_USERNAME_EMAIL;
    public static final Index USER_EMAIL_INDEX = Indexes0.USER_EMAIL_INDEX;
    public static final Index USER_SESSIONID_INDEX = Indexes0.USER_SESSIONID_INDEX;
    public static final Index USER_TOKEN_INDEX = Indexes0.USER_TOKEN_INDEX;
    public static final Index USER_USERNAME_INDEX = Indexes0.USER_USERNAME_INDEX;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADMIN_PKEY = Internal.createIndex("admin_pkey", Admin.ADMIN, new OrderField[]{Admin.ADMIN.ID}, true);
        public static Index ATTENDANCE_PKEY = Internal.createIndex("attendance_pkey", Attendance.ATTENDANCE, new OrderField[]{Attendance.ATTENDANCE.LECTURE_FID, Attendance.ATTENDANCE.STUDENT_FID}, true);
        public static Index CLASS_ROOM_NAME = Internal.createIndex("class_room_name", ClassRoom.CLASS_ROOM, new OrderField[]{ClassRoom.CLASS_ROOM.NAME}, true);
        public static Index CLASS_ROOM_NAME_INDEX = Internal.createIndex("class_room_name_index", ClassRoom.CLASS_ROOM, new OrderField[]{ClassRoom.CLASS_ROOM.NAME}, false);
        public static Index CLASS_ROOM_PKEY = Internal.createIndex("class_room_pkey", ClassRoom.CLASS_ROOM, new OrderField[]{ClassRoom.CLASS_ROOM.ID}, true);
        public static Index CLASS_TEACHER_CLASS_ROOM_LINK_PKEY = Internal.createIndex("class_teacher_class_room_link_pkey", ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK, new OrderField[]{ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK.CLASS_TEACHER_FID}, true);
        public static Index COURSE_NAME_INDEX = Internal.createIndex("course_name_index", Course.COURSE, new OrderField[]{Course.COURSE.NAME}, false);
        public static Index COURSE_PKEY = Internal.createIndex("course_pkey", Course.COURSE, new OrderField[]{Course.COURSE.ID}, true);
        public static Index UNIQUE_COURSE_NAME = Internal.createIndex("unique_course_name", Course.COURSE, new OrderField[]{Course.COURSE.NAME}, true);
        public static Index DEPARTMENT_NAME_INDEX = Internal.createIndex("department_name_index", Department.DEPARTMENT, new OrderField[]{Department.DEPARTMENT.NAME}, false);
        public static Index DEPARTMENT_PKEY = Internal.createIndex("department_pkey", Department.DEPARTMENT, new OrderField[]{Department.DEPARTMENT.ID}, true);
        public static Index DEPARTMENT_UNIQUE_NAME = Internal.createIndex("department_unique_name", Department.DEPARTMENT, new OrderField[]{Department.DEPARTMENT.NAME}, true);
        public static Index LECTURE_PKEY = Internal.createIndex("lecture_pkey", Lecture.LECTURE, new OrderField[]{Lecture.LECTURE.ID}, true);
        public static Index STUDENT_NAME_INDEX = Internal.createIndex("student_name_index", Student.STUDENT, new OrderField[]{Student.STUDENT.FIRST_NAME, Student.STUDENT.LAST_NAME}, false);
        public static Index STUDENT_PKEY = Internal.createIndex("student_pkey", Student.STUDENT, new OrderField[]{Student.STUDENT.ID}, true);
        public static Index STUDENT_SUBJECT_LINK_PKEY = Internal.createIndex("student_subject_link_pkey", StudentSubjectLink.STUDENT_SUBJECT_LINK, new OrderField[]{StudentSubjectLink.STUDENT_SUBJECT_LINK.STUDENT_FID, StudentSubjectLink.STUDENT_SUBJECT_LINK.SUBJECT_FID}, true);
        public static Index SUBJECT_PKEY = Internal.createIndex("subject_pkey", Subject.SUBJECT, new OrderField[]{Subject.SUBJECT.ID}, true);
        public static Index SUBJECT_CLASS_LINK_PKEY = Internal.createIndex("subject_class_link_pkey", SubjectClassLink.SUBJECT_CLASS_LINK, new OrderField[]{SubjectClassLink.SUBJECT_CLASS_LINK.CLASS_ROOM_FID, SubjectClassLink.SUBJECT_CLASS_LINK.SUBJECT_FID}, true);
        public static Index TCS_CLASS_ROOM_INDEX = Internal.createIndex("tcs_class_room_index", Tcs.TCS, new OrderField[]{Tcs.TCS.CLASS_ROOM_FID}, false);
        public static Index TCS_PKEY = Internal.createIndex("tcs_pkey", Tcs.TCS, new OrderField[]{Tcs.TCS.CLASS_ROOM_FID, Tcs.TCS.SUBJECT_FID}, true);
        public static Index TCS_SUBJECT_INDEX = Internal.createIndex("tcs_subject_index", Tcs.TCS, new OrderField[]{Tcs.TCS.SUBJECT_FID}, false);
        public static Index TCS_TEACHER_INDEX = Internal.createIndex("tcs_teacher_index", Tcs.TCS, new OrderField[]{Tcs.TCS.TEACHER_FID}, false);
        public static Index TEACHER_NAME_INDEX = Internal.createIndex("teacher_name_index", Teacher.TEACHER, new OrderField[]{Teacher.TEACHER.FIRST_NAME, Teacher.TEACHER.LAST_NAME}, false);
        public static Index TEACHER_PKEY = Internal.createIndex("teacher_pkey", Teacher.TEACHER, new OrderField[]{Teacher.TEACHER.ID}, true);
        public static Index TEACHER_DEPARTMENT_LINK_PKEY = Internal.createIndex("teacher_department_link_pkey", TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK, new OrderField[]{TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.DEPARTMENT_FID, TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.TEACHER_FID}, true);
        public static Index UNIQUE_USER_EMAIL = Internal.createIndex("unique_user_email", Users.USERS, new OrderField[]{Users.USERS.EMAIL}, true);
        public static Index UNIQUE_USER_USERNAME = Internal.createIndex("unique_user_username", Users.USERS, new OrderField[]{Users.USERS.USERNAME}, true);
        public static Index UNIQUE_USER_USERNAME_EMAIL = Internal.createIndex("unique_user_username_email", Users.USERS, new OrderField[]{Users.USERS.USERNAME, Users.USERS.EMAIL}, true);
        public static Index USER_EMAIL_INDEX = Internal.createIndex("user_email_index", Users.USERS, new OrderField[]{Users.USERS.EMAIL}, false);
        public static Index USER_SESSIONID_INDEX = Internal.createIndex("user_sessionid_index", Users.USERS, new OrderField[]{Users.USERS.SESSION_ID}, false);
        public static Index USER_TOKEN_INDEX = Internal.createIndex("user_token_index", Users.USERS, new OrderField[]{Users.USERS.TOKEN}, false);
        public static Index USER_USERNAME_INDEX = Internal.createIndex("user_username_index", Users.USERS, new OrderField[]{Users.USERS.USERNAME}, false);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[]{Users.USERS.ID}, true);
    }
}
