/*
 * This file is generated by jOOQ.
 */
package jooq.entities;


import jooq.entities.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADMIN_PKEY = Indexes0.ADMIN_PKEY;
    public static final Index ATTENDANCE_PKEY = Indexes0.ATTENDANCE_PKEY;
    public static final Index CLASS_PKEY = Indexes0.CLASS_PKEY;
    public static final Index COURSE_PKEY = Indexes0.COURSE_PKEY;
    public static final Index DEPARTMENT_PKEY = Indexes0.DEPARTMENT_PKEY;
    public static final Index LECTURE_PKEY = Indexes0.LECTURE_PKEY;
    public static final Index STUDENT_PKEY = Indexes0.STUDENT_PKEY;
    public static final Index STUDENT_SUBJECT_LINK_PKEY = Indexes0.STUDENT_SUBJECT_LINK_PKEY;
    public static final Index SUBJECT_PKEY = Indexes0.SUBJECT_PKEY;
    public static final Index SUBJECT_CLASS_LINK_PKEY = Indexes0.SUBJECT_CLASS_LINK_PKEY;
    public static final Index TCS_PKEY = Indexes0.TCS_PKEY;
    public static final Index TCS_UNIQUE_CONSTRAINT = Indexes0.TCS_UNIQUE_CONSTRAINT;
    public static final Index TEACHER_PKEY = Indexes0.TEACHER_PKEY;
    public static final Index TEACHER_DEPARTMENT_LINK_PKEY = Indexes0.TEACHER_DEPARTMENT_LINK_PKEY;
    public static final Index UK_6DOTKOTT2KJSP8VW4D0M25FB7 = Indexes0.UK_6DOTKOTT2KJSP8VW4D0M25FB7;
    public static final Index UK_R43AF9AP4EDM43MMTQ01ODDJ6 = Indexes0.UK_R43AF9AP4EDM43MMTQ01ODDJ6;
    public static final Index USERS_PKEY = Indexes0.USERS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADMIN_PKEY = Internal.createIndex("admin_pkey", Admin.ADMIN, new OrderField[] { Admin.ADMIN.ID }, true);
        public static Index ATTENDANCE_PKEY = Internal.createIndex("attendance_pkey", Attendance.ATTENDANCE, new OrderField[] { Attendance.ATTENDANCE.LECTURE_FID, Attendance.ATTENDANCE.STUDENT_FID }, true);
        public static Index CLASS_PKEY = Internal.createIndex("class_pkey", ClassRoom.CLASS_ROOM, new OrderField[] { ClassRoom.CLASS_ROOM.ID }, true);
        public static Index COURSE_PKEY = Internal.createIndex("course_pkey", Course.COURSE, new OrderField[] { Course.COURSE.ID }, true);
        public static Index DEPARTMENT_PKEY = Internal.createIndex("department_pkey", Department.DEPARTMENT, new OrderField[] { Department.DEPARTMENT.ID }, true);
        public static Index LECTURE_PKEY = Internal.createIndex("lecture_pkey", Lecture.LECTURE, new OrderField[] { Lecture.LECTURE.ID }, true);
        public static Index STUDENT_PKEY = Internal.createIndex("student_pkey", Student.STUDENT, new OrderField[] { Student.STUDENT.ID }, true);
        public static Index STUDENT_SUBJECT_LINK_PKEY = Internal.createIndex("student_subject_link_pkey", StudentSubjectLink.STUDENT_SUBJECT_LINK, new OrderField[] { StudentSubjectLink.STUDENT_SUBJECT_LINK.STUDENT_FID, StudentSubjectLink.STUDENT_SUBJECT_LINK.SUBJECT_FID }, true);
        public static Index SUBJECT_PKEY = Internal.createIndex("subject_pkey", Subject.SUBJECT, new OrderField[] { Subject.SUBJECT.ID }, true);
        public static Index SUBJECT_CLASS_LINK_PKEY = Internal.createIndex("subject_class_link_pkey", SubjectClassLink.SUBJECT_CLASS_LINK, new OrderField[] { SubjectClassLink.SUBJECT_CLASS_LINK.CLASS_FID, SubjectClassLink.SUBJECT_CLASS_LINK.SUBJECT_FID }, true);
        public static Index TCS_PKEY = Internal.createIndex("tcs_pkey", Tcs.TCS, new OrderField[] { Tcs.TCS.ID }, true);
        public static Index TCS_UNIQUE_CONSTRAINT = Internal.createIndex("tcs_unique_constraint", Tcs.TCS, new OrderField[] { Tcs.TCS.TEACHER_FID, Tcs.TCS.CLASS_FID, Tcs.TCS.SUBJECT_FID }, true);
        public static Index TEACHER_PKEY = Internal.createIndex("teacher_pkey", Teacher.TEACHER, new OrderField[] { Teacher.TEACHER.ID }, true);
        public static Index TEACHER_DEPARTMENT_LINK_PKEY = Internal.createIndex("teacher_department_link_pkey", TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK, new OrderField[] { TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.TEACHER_FID, TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.DEPARTMENT_FID }, true);
        public static Index UK_6DOTKOTT2KJSP8VW4D0M25FB7 = Internal.createIndex("uk_6dotkott2kjsp8vw4d0m25fb7", Users.USERS, new OrderField[] { Users.USERS.EMAIL }, true);
        public static Index UK_R43AF9AP4EDM43MMTQ01ODDJ6 = Internal.createIndex("uk_r43af9ap4edm43mmtq01oddj6", Users.USERS, new OrderField[] { Users.USERS.USERNAME }, true);
        public static Index USERS_PKEY = Internal.createIndex("users_pkey", Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    }
}
