/*
 * This file is generated by jOOQ.
 */
package jooq.entities;


import jooq.entities.tables.*;
import jooq.entities.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>public</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.12"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminRecord> ADMIN_PKEY = UniqueKeys0.ADMIN_PKEY;
    public static final UniqueKey<AttendanceRecord> ATTENDANCE_PKEY = UniqueKeys0.ATTENDANCE_PKEY;
    public static final UniqueKey<ClassRoomRecord> CLASS_ROOM_PKEY = UniqueKeys0.CLASS_ROOM_PKEY;
    public static final UniqueKey<ClassRoomRecord> CLASS_ROOM_NAME = UniqueKeys0.CLASS_ROOM_NAME;
    public static final UniqueKey<ClassTeacherClassRoomLinkRecord> CLASS_TEACHER_CLASS_ROOM_LINK_PKEY = UniqueKeys0.CLASS_TEACHER_CLASS_ROOM_LINK_PKEY;
    public static final UniqueKey<CourseRecord> COURSE_PKEY = UniqueKeys0.COURSE_PKEY;
    public static final UniqueKey<CourseRecord> UNIQUE_COURSE_NAME = UniqueKeys0.UNIQUE_COURSE_NAME;
    public static final UniqueKey<DepartmentRecord> DEPARTMENT_PKEY = UniqueKeys0.DEPARTMENT_PKEY;
    public static final UniqueKey<DepartmentRecord> DEPARTMENT_UNIQUE_NAME = UniqueKeys0.DEPARTMENT_UNIQUE_NAME;
    public static final UniqueKey<LectureRecord> LECTURE_PKEY = UniqueKeys0.LECTURE_PKEY;
    public static final UniqueKey<StudentRecord> STUDENT_PKEY = UniqueKeys0.STUDENT_PKEY;
    public static final UniqueKey<StudentSubjectLinkRecord> STUDENT_SUBJECT_LINK_PKEY = UniqueKeys0.STUDENT_SUBJECT_LINK_PKEY;
    public static final UniqueKey<SubjectRecord> SUBJECT_PKEY = UniqueKeys0.SUBJECT_PKEY;
    public static final UniqueKey<SubjectClassLinkRecord> SUBJECT_CLASS_LINK_PKEY = UniqueKeys0.SUBJECT_CLASS_LINK_PKEY;
    public static final UniqueKey<TcsRecord> TCS_PKEY = UniqueKeys0.TCS_PKEY;
    public static final UniqueKey<TeacherRecord> TEACHER_PKEY = UniqueKeys0.TEACHER_PKEY;
    public static final UniqueKey<TeacherDepartmentLinkRecord> TEACHER_DEPARTMENT_LINK_PKEY = UniqueKeys0.TEACHER_DEPARTMENT_LINK_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<UsersRecord> UNIQUE_USER_EMAIL = UniqueKeys0.UNIQUE_USER_EMAIL;
    public static final UniqueKey<UsersRecord> UNIQUE_USER_USERNAME_EMAIL = UniqueKeys0.UNIQUE_USER_USERNAME_EMAIL;
    public static final UniqueKey<UsersRecord> UNIQUE_USER_USERNAME = UniqueKeys0.UNIQUE_USER_USERNAME;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AdminRecord, UsersRecord> ADMIN__USER_ADMIN_FOREIGN_KEY = ForeignKeys0.ADMIN__USER_ADMIN_FOREIGN_KEY;
    public static final ForeignKey<AttendanceRecord, LectureRecord> ATTENDANCE__LECTURE_FOREIGN_KEY = ForeignKeys0.ATTENDANCE__LECTURE_FOREIGN_KEY;
    public static final ForeignKey<AttendanceRecord, StudentRecord> ATTENDANCE__STUDENT_FOREIGN_KEY = ForeignKeys0.ATTENDANCE__STUDENT_FOREIGN_KEY;
    public static final ForeignKey<ClassRoomRecord, CourseRecord> CLASS_ROOM__CLASS_COURSE_FOREIGN_KEY = ForeignKeys0.CLASS_ROOM__CLASS_COURSE_FOREIGN_KEY;
    public static final ForeignKey<ClassTeacherClassRoomLinkRecord, ClassRoomRecord> CLASS_TEACHER_CLASS_ROOM_LINK__FKRU9WJA4OMJPPTDDT9AUGUICFH = ForeignKeys0.CLASS_TEACHER_CLASS_ROOM_LINK__FKRU9WJA4OMJPPTDDT9AUGUICFH;
    public static final ForeignKey<ClassTeacherClassRoomLinkRecord, TeacherRecord> CLASS_TEACHER_CLASS_ROOM_LINK__FKGEXE1EQJ2QGG9OT3MMIB20YWF = ForeignKeys0.CLASS_TEACHER_CLASS_ROOM_LINK__FKGEXE1EQJ2QGG9OT3MMIB20YWF;
    public static final ForeignKey<CourseRecord, DepartmentRecord> COURSE__DEPARTMENT_FOREIGN_KEY = ForeignKeys0.COURSE__DEPARTMENT_FOREIGN_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AdminRecord> ADMIN_PKEY = Internal.createUniqueKey(Admin.ADMIN, "admin_pkey", Admin.ADMIN.ID);
        public static final UniqueKey<AttendanceRecord> ATTENDANCE_PKEY = Internal.createUniqueKey(Attendance.ATTENDANCE, "attendance_pkey", Attendance.ATTENDANCE.LECTURE_FID, Attendance.ATTENDANCE.STUDENT_FID);
        public static final UniqueKey<ClassRoomRecord> CLASS_ROOM_PKEY = Internal.createUniqueKey(ClassRoom.CLASS_ROOM, "class_room_pkey", ClassRoom.CLASS_ROOM.ID);
        public static final UniqueKey<ClassRoomRecord> CLASS_ROOM_NAME = Internal.createUniqueKey(ClassRoom.CLASS_ROOM, "class_room_name", ClassRoom.CLASS_ROOM.NAME);
        public static final UniqueKey<ClassTeacherClassRoomLinkRecord> CLASS_TEACHER_CLASS_ROOM_LINK_PKEY = Internal.createUniqueKey(ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK, "class_teacher_class_room_link_pkey", ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK.CLASS_TEACHER_FID);
        public static final UniqueKey<CourseRecord> COURSE_PKEY = Internal.createUniqueKey(Course.COURSE, "course_pkey", Course.COURSE.ID);
        public static final UniqueKey<CourseRecord> UNIQUE_COURSE_NAME = Internal.createUniqueKey(Course.COURSE, "unique_course_name", Course.COURSE.NAME);
        public static final UniqueKey<DepartmentRecord> DEPARTMENT_PKEY = Internal.createUniqueKey(Department.DEPARTMENT, "department_pkey", Department.DEPARTMENT.ID);
        public static final UniqueKey<DepartmentRecord> DEPARTMENT_UNIQUE_NAME = Internal.createUniqueKey(Department.DEPARTMENT, "department_unique_name", Department.DEPARTMENT.NAME);
        public static final UniqueKey<LectureRecord> LECTURE_PKEY = Internal.createUniqueKey(Lecture.LECTURE, "lecture_pkey", Lecture.LECTURE.ID);
        public static final UniqueKey<StudentRecord> STUDENT_PKEY = Internal.createUniqueKey(Student.STUDENT, "student_pkey", Student.STUDENT.ID);
        public static final UniqueKey<StudentSubjectLinkRecord> STUDENT_SUBJECT_LINK_PKEY = Internal.createUniqueKey(StudentSubjectLink.STUDENT_SUBJECT_LINK, "student_subject_link_pkey", StudentSubjectLink.STUDENT_SUBJECT_LINK.STUDENT_FID, StudentSubjectLink.STUDENT_SUBJECT_LINK.SUBJECT_FID);
        public static final UniqueKey<SubjectRecord> SUBJECT_PKEY = Internal.createUniqueKey(Subject.SUBJECT, "subject_pkey", Subject.SUBJECT.ID);
        public static final UniqueKey<SubjectClassLinkRecord> SUBJECT_CLASS_LINK_PKEY = Internal.createUniqueKey(SubjectClassLink.SUBJECT_CLASS_LINK, "subject_class_link_pkey", SubjectClassLink.SUBJECT_CLASS_LINK.CLASS_ROOM_FID, SubjectClassLink.SUBJECT_CLASS_LINK.SUBJECT_FID);
        public static final UniqueKey<TcsRecord> TCS_PKEY = Internal.createUniqueKey(Tcs.TCS, "tcs_pkey", Tcs.TCS.CLASS_ROOM_FID, Tcs.TCS.SUBJECT_FID);
        public static final UniqueKey<TeacherRecord> TEACHER_PKEY = Internal.createUniqueKey(Teacher.TEACHER, "teacher_pkey", Teacher.TEACHER.ID);
        public static final UniqueKey<TeacherDepartmentLinkRecord> TEACHER_DEPARTMENT_LINK_PKEY = Internal.createUniqueKey(TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK, "teacher_department_link_pkey", TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.DEPARTMENT_FID, TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.TEACHER_FID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> UNIQUE_USER_EMAIL = Internal.createUniqueKey(Users.USERS, "unique_user_email", Users.USERS.EMAIL);
        public static final UniqueKey<UsersRecord> UNIQUE_USER_USERNAME_EMAIL = Internal.createUniqueKey(Users.USERS, "unique_user_username_email", Users.USERS.USERNAME, Users.USERS.EMAIL);
        public static final UniqueKey<UsersRecord> UNIQUE_USER_USERNAME = Internal.createUniqueKey(Users.USERS, "unique_user_username", Users.USERS.USERNAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AdminRecord, UsersRecord> ADMIN__USER_ADMIN_FOREIGN_KEY = Internal.createForeignKey(Keys.USERS_PKEY, Admin.ADMIN, "admin__user_admin_foreign_key", Admin.ADMIN.ID);
        public static final ForeignKey<AttendanceRecord, LectureRecord> ATTENDANCE__LECTURE_FOREIGN_KEY = Internal.createForeignKey(Keys.LECTURE_PKEY, Attendance.ATTENDANCE, "attendance__lecture_foreign_key", Attendance.ATTENDANCE.LECTURE_FID);
        public static final ForeignKey<AttendanceRecord, StudentRecord> ATTENDANCE__STUDENT_FOREIGN_KEY = Internal.createForeignKey(Keys.STUDENT_PKEY, Attendance.ATTENDANCE, "attendance__student_foreign_key", Attendance.ATTENDANCE.STUDENT_FID);
        public static final ForeignKey<ClassRoomRecord, CourseRecord> CLASS_ROOM__CLASS_COURSE_FOREIGN_KEY = Internal.createForeignKey(Keys.COURSE_PKEY, ClassRoom.CLASS_ROOM, "class_room__class_course_foreign_key", ClassRoom.CLASS_ROOM.COURSE_FID);
        public static final ForeignKey<ClassTeacherClassRoomLinkRecord, ClassRoomRecord> CLASS_TEACHER_CLASS_ROOM_LINK__FKRU9WJA4OMJPPTDDT9AUGUICFH = Internal.createForeignKey(Keys.CLASS_ROOM_PKEY, ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK, "class_teacher_class_room_link__fkru9wja4omjpptddt9auguicfh", ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK.CLASS_ROOM_FID);
        public static final ForeignKey<ClassTeacherClassRoomLinkRecord, TeacherRecord> CLASS_TEACHER_CLASS_ROOM_LINK__FKGEXE1EQJ2QGG9OT3MMIB20YWF = Internal.createForeignKey(Keys.TEACHER_PKEY, ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK, "class_teacher_class_room_link__fkgexe1eqj2qgg9ot3mmib20ywf", ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK.CLASS_TEACHER_FID);
        public static final ForeignKey<CourseRecord, DepartmentRecord> COURSE__DEPARTMENT_FOREIGN_KEY = Internal.createForeignKey(Keys.DEPARTMENT_PKEY, Course.COURSE, "course__department_foreign_key", Course.COURSE.DEPARTMENT_FID);
    }
}
