/*
 * This file is generated by jOOQ.
 */
package jooq.entities;


import jooq.entities.tables.*;
import jooq.entities.tables.records.*;
import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AdminRecord> ADMIN_PKEY = UniqueKeys0.ADMIN_PKEY;
    public static final UniqueKey<AttendanceRecord> ATTENDANCE_PKEY = UniqueKeys0.ATTENDANCE_PKEY;
    public static final UniqueKey<ClassRoomRecord> CLASS_PKEY = UniqueKeys0.CLASS_PKEY;
    public static final UniqueKey<CourseRecord> COURSE_PKEY = UniqueKeys0.COURSE_PKEY;
    public static final UniqueKey<DepartmentRecord> DEPARTMENT_PKEY = UniqueKeys0.DEPARTMENT_PKEY;
    public static final UniqueKey<LectureRecord> LECTURE_PKEY = UniqueKeys0.LECTURE_PKEY;
    public static final UniqueKey<StudentRecord> STUDENT_PKEY = UniqueKeys0.STUDENT_PKEY;
    public static final UniqueKey<StudentSubjectLinkRecord> STUDENT_SUBJECT_LINK_PKEY = UniqueKeys0.STUDENT_SUBJECT_LINK_PKEY;
    public static final UniqueKey<SubjectRecord> SUBJECT_PKEY = UniqueKeys0.SUBJECT_PKEY;
    public static final UniqueKey<SubjectClassLinkRecord> SUBJECT_CLASS_LINK_PKEY = UniqueKeys0.SUBJECT_CLASS_LINK_PKEY;
    public static final UniqueKey<TcsRecord> TCS_PKEY = UniqueKeys0.TCS_PKEY;
    public static final UniqueKey<TcsRecord> TCS_UNIQUE_CONSTRAINT = UniqueKeys0.TCS_UNIQUE_CONSTRAINT;
    public static final UniqueKey<TeacherRecord> TEACHER_PKEY = UniqueKeys0.TEACHER_PKEY;
    public static final UniqueKey<TeacherDepartmentLinkRecord> TEACHER_DEPARTMENT_LINK_PKEY = UniqueKeys0.TEACHER_DEPARTMENT_LINK_PKEY;
    public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
    public static final UniqueKey<UsersRecord> UK_6DOTKOTT2KJSP8VW4D0M25FB7 = UniqueKeys0.UK_6DOTKOTT2KJSP8VW4D0M25FB7;
    public static final UniqueKey<UsersRecord> UK_R43AF9AP4EDM43MMTQ01ODDJ6 = UniqueKeys0.UK_R43AF9AP4EDM43MMTQ01ODDJ6;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AdminRecord, UsersRecord> ADMIN__USER_FOREIGN_KEY = ForeignKeys0.ADMIN__USER_FOREIGN_KEY;
    public static final ForeignKey<AttendanceRecord, LectureRecord> ATTENDANCE__LECTURE_FOREIGN_KEY = ForeignKeys0.ATTENDANCE__LECTURE_FOREIGN_KEY;
    public static final ForeignKey<AttendanceRecord, StudentRecord> ATTENDANCE__STUDENT_FOREIGN_KEY = ForeignKeys0.ATTENDANCE__STUDENT_FOREIGN_KEY;
    public static final ForeignKey<ClassRoomRecord, CourseRecord> CLASS_ROOM__CLASS_COURSE_FOREIGN_KEY = ForeignKeys0.CLASS_ROOM__CLASS_COURSE_FOREIGN_KEY;
    public static final ForeignKey<CourseRecord, DepartmentRecord> COURSE__DEPARTMENT_FOREIGN_KEY = ForeignKeys0.COURSE__DEPARTMENT_FOREIGN_KEY;
    public static final ForeignKey<DepartmentRecord, TeacherRecord> DEPARTMENT__DEPARTMENT_HOD_TEACHER_FOREIGN_KEY = ForeignKeys0.DEPARTMENT__DEPARTMENT_HOD_TEACHER_FOREIGN_KEY;
    public static final ForeignKey<LectureRecord, TcsRecord> LECTURE__LECTURE_TCS_FOREIGN_KEY = ForeignKeys0.LECTURE__LECTURE_TCS_FOREIGN_KEY;
    public static final ForeignKey<StudentRecord, UsersRecord> STUDENT__FK3W7XMT19I6A0CR7KP8C80EK40 = ForeignKeys0.STUDENT__FK3W7XMT19I6A0CR7KP8C80EK40;
    public static final ForeignKey<StudentRecord, ClassRoomRecord> STUDENT__STUDENT_FOREIGN_KEY = ForeignKeys0.STUDENT__STUDENT_FOREIGN_KEY;
    public static final ForeignKey<StudentSubjectLinkRecord, StudentRecord> STUDENT_SUBJECT_LINK__STUDENT_SUBJECT_LINK_STUDENT_FOREIGN_KEY = ForeignKeys0.STUDENT_SUBJECT_LINK__STUDENT_SUBJECT_LINK_STUDENT_FOREIGN_KEY;
    public static final ForeignKey<StudentSubjectLinkRecord, SubjectRecord> STUDENT_SUBJECT_LINK__STUDENT_SUBJECT_LINK_SUBJECT_FOREIGN_KEY = ForeignKeys0.STUDENT_SUBJECT_LINK__STUDENT_SUBJECT_LINK_SUBJECT_FOREIGN_KEY;
    public static final ForeignKey<SubjectRecord, CourseRecord> SUBJECT__SUBJECT_COURSE_FOREIGN_KEY = ForeignKeys0.SUBJECT__SUBJECT_COURSE_FOREIGN_KEY;
    public static final ForeignKey<SubjectClassLinkRecord, ClassRoomRecord> SUBJECT_CLASS_LINK__SUBJECT_CLASS_LINK_CLASS_FOREIGN_KEY = ForeignKeys0.SUBJECT_CLASS_LINK__SUBJECT_CLASS_LINK_CLASS_FOREIGN_KEY;
    public static final ForeignKey<SubjectClassLinkRecord, SubjectRecord> SUBJECT_CLASS_LINK__SUBJECT_CLASS_LINK_SUBJECT_FOREIGN_KEY = ForeignKeys0.SUBJECT_CLASS_LINK__SUBJECT_CLASS_LINK_SUBJECT_FOREIGN_KEY;
    public static final ForeignKey<TcsRecord, ClassRoomRecord> TCS__TCS_CLASS_FOREIGN_KEY = ForeignKeys0.TCS__TCS_CLASS_FOREIGN_KEY;
    public static final ForeignKey<TcsRecord, SubjectRecord> TCS__TCS_SUBJECT_FOREIGN_KEY = ForeignKeys0.TCS__TCS_SUBJECT_FOREIGN_KEY;
    public static final ForeignKey<TcsRecord, TeacherRecord> TCS__TCS_TEACHER_FOREIGN_KEY = ForeignKeys0.TCS__TCS_TEACHER_FOREIGN_KEY;
    public static final ForeignKey<TeacherRecord, UsersRecord> TEACHER__FKSPQY2S83GVL6G8NT5AUBLS90K = ForeignKeys0.TEACHER__FKSPQY2S83GVL6G8NT5AUBLS90K;
    public static final ForeignKey<TeacherRecord, ClassRoomRecord> TEACHER__CLASS_TEACHER_CLASS_FOREIGN_KEY = ForeignKeys0.TEACHER__CLASS_TEACHER_CLASS_FOREIGN_KEY;
    public static final ForeignKey<TeacherDepartmentLinkRecord, TeacherRecord> TEACHER_DEPARTMENT_LINK__TEACHER_DEPARTMENT_LINK_TEACHER_FOREIGN_KEY = ForeignKeys0.TEACHER_DEPARTMENT_LINK__TEACHER_DEPARTMENT_LINK_TEACHER_FOREIGN_KEY;
    public static final ForeignKey<TeacherDepartmentLinkRecord, DepartmentRecord> TEACHER_DEPARTMENT_LINK__TEACHER_DEPARTMENT_LINK_DEPARTMENT_FOREIGN_KEY = ForeignKeys0.TEACHER_DEPARTMENT_LINK__TEACHER_DEPARTMENT_LINK_DEPARTMENT_FOREIGN_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AdminRecord> ADMIN_PKEY = Internal.createUniqueKey(Admin.ADMIN, "admin_pkey", Admin.ADMIN.ID);
        public static final UniqueKey<AttendanceRecord> ATTENDANCE_PKEY = Internal.createUniqueKey(Attendance.ATTENDANCE, "attendance_pkey", Attendance.ATTENDANCE.LECTURE_FID, Attendance.ATTENDANCE.STUDENT_FID);
        public static final UniqueKey<ClassRoomRecord> CLASS_PKEY = Internal.createUniqueKey(ClassRoom.CLASS_ROOM, "class_pkey", ClassRoom.CLASS_ROOM.ID);
        public static final UniqueKey<CourseRecord> COURSE_PKEY = Internal.createUniqueKey(Course.COURSE, "course_pkey", Course.COURSE.ID);
        public static final UniqueKey<DepartmentRecord> DEPARTMENT_PKEY = Internal.createUniqueKey(Department.DEPARTMENT, "department_pkey", Department.DEPARTMENT.ID);
        public static final UniqueKey<LectureRecord> LECTURE_PKEY = Internal.createUniqueKey(Lecture.LECTURE, "lecture_pkey", Lecture.LECTURE.ID);
        public static final UniqueKey<StudentRecord> STUDENT_PKEY = Internal.createUniqueKey(Student.STUDENT, "student_pkey", Student.STUDENT.ID);
        public static final UniqueKey<StudentSubjectLinkRecord> STUDENT_SUBJECT_LINK_PKEY = Internal.createUniqueKey(StudentSubjectLink.STUDENT_SUBJECT_LINK, "student_subject_link_pkey", StudentSubjectLink.STUDENT_SUBJECT_LINK.STUDENT_FID, StudentSubjectLink.STUDENT_SUBJECT_LINK.SUBJECT_FID);
        public static final UniqueKey<SubjectRecord> SUBJECT_PKEY = Internal.createUniqueKey(Subject.SUBJECT, "subject_pkey", Subject.SUBJECT.ID);
        public static final UniqueKey<SubjectClassLinkRecord> SUBJECT_CLASS_LINK_PKEY = Internal.createUniqueKey(SubjectClassLink.SUBJECT_CLASS_LINK, "subject_class_link_pkey", SubjectClassLink.SUBJECT_CLASS_LINK.CLASS_FID, SubjectClassLink.SUBJECT_CLASS_LINK.SUBJECT_FID);
        public static final UniqueKey<TcsRecord> TCS_PKEY = Internal.createUniqueKey(Tcs.TCS, "tcs_pkey", Tcs.TCS.ID);
        public static final UniqueKey<TcsRecord> TCS_UNIQUE_CONSTRAINT = Internal.createUniqueKey(Tcs.TCS, "tcs_unique_constraint", Tcs.TCS.TEACHER_FID, Tcs.TCS.CLASS_FID, Tcs.TCS.SUBJECT_FID);
        public static final UniqueKey<TeacherRecord> TEACHER_PKEY = Internal.createUniqueKey(Teacher.TEACHER, "teacher_pkey", Teacher.TEACHER.ID);
        public static final UniqueKey<TeacherDepartmentLinkRecord> TEACHER_DEPARTMENT_LINK_PKEY = Internal.createUniqueKey(TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK, "teacher_department_link_pkey", TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.TEACHER_FID, TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.DEPARTMENT_FID);
        public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, "users_pkey", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> UK_6DOTKOTT2KJSP8VW4D0M25FB7 = Internal.createUniqueKey(Users.USERS, "uk_6dotkott2kjsp8vw4d0m25fb7", Users.USERS.EMAIL);
        public static final UniqueKey<UsersRecord> UK_R43AF9AP4EDM43MMTQ01ODDJ6 = Internal.createUniqueKey(Users.USERS, "uk_r43af9ap4edm43mmtq01oddj6", Users.USERS.USERNAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AdminRecord, UsersRecord> ADMIN__USER_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.USERS_PKEY, Admin.ADMIN, "admin__user_foreign_key", Admin.ADMIN.ID);
        public static final ForeignKey<AttendanceRecord, LectureRecord> ATTENDANCE__LECTURE_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.LECTURE_PKEY, Attendance.ATTENDANCE, "attendance__lecture_foreign_key", Attendance.ATTENDANCE.LECTURE_FID);
        public static final ForeignKey<AttendanceRecord, StudentRecord> ATTENDANCE__STUDENT_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.STUDENT_PKEY, Attendance.ATTENDANCE, "attendance__student_foreign_key", Attendance.ATTENDANCE.STUDENT_FID);
        public static final ForeignKey<ClassRoomRecord, CourseRecord> CLASS_ROOM__CLASS_COURSE_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.COURSE_PKEY, ClassRoom.CLASS_ROOM, "class_room__class_course_foreign_key", ClassRoom.CLASS_ROOM.COURSE_FID);
        public static final ForeignKey<CourseRecord, DepartmentRecord> COURSE__DEPARTMENT_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.DEPARTMENT_PKEY, Course.COURSE, "course__department_foreign_key", Course.COURSE.DEPARTMENT_FID);
        public static final ForeignKey<DepartmentRecord, TeacherRecord> DEPARTMENT__DEPARTMENT_HOD_TEACHER_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.TEACHER_PKEY, Department.DEPARTMENT, "department__department_hod_teacher_foreign_key", Department.DEPARTMENT.HOD_TEACHER_FID);
        public static final ForeignKey<LectureRecord, TcsRecord> LECTURE__LECTURE_TCS_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.TCS_PKEY, Lecture.LECTURE, "lecture__lecture_tcs_foreign_key", Lecture.LECTURE.TCS_FID);
        public static final ForeignKey<StudentRecord, UsersRecord> STUDENT__FK3W7XMT19I6A0CR7KP8C80EK40 = Internal.createForeignKey(jooq.entities.Keys.USERS_PKEY, Student.STUDENT, "student__fk3w7xmt19i6a0cr7kp8c80ek40", Student.STUDENT.ID);
        public static final ForeignKey<StudentRecord, ClassRoomRecord> STUDENT__STUDENT_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.CLASS_PKEY, Student.STUDENT, "student__student_foreign_key", Student.STUDENT.CLASS_FID);
        public static final ForeignKey<StudentSubjectLinkRecord, StudentRecord> STUDENT_SUBJECT_LINK__STUDENT_SUBJECT_LINK_STUDENT_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.STUDENT_PKEY, StudentSubjectLink.STUDENT_SUBJECT_LINK, "student_subject_link__student_subject_link_student_foreign_key", StudentSubjectLink.STUDENT_SUBJECT_LINK.STUDENT_FID);
        public static final ForeignKey<StudentSubjectLinkRecord, SubjectRecord> STUDENT_SUBJECT_LINK__STUDENT_SUBJECT_LINK_SUBJECT_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.SUBJECT_PKEY, StudentSubjectLink.STUDENT_SUBJECT_LINK, "student_subject_link__student_subject_link_subject_foreign_key", StudentSubjectLink.STUDENT_SUBJECT_LINK.SUBJECT_FID);
        public static final ForeignKey<SubjectRecord, CourseRecord> SUBJECT__SUBJECT_COURSE_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.COURSE_PKEY, Subject.SUBJECT, "subject__subject_course_foreign_key", Subject.SUBJECT.COURSE_FID);
        public static final ForeignKey<SubjectClassLinkRecord, ClassRoomRecord> SUBJECT_CLASS_LINK__SUBJECT_CLASS_LINK_CLASS_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.CLASS_PKEY, SubjectClassLink.SUBJECT_CLASS_LINK, "subject_class_link__subject_class_link_class_foreign_key", SubjectClassLink.SUBJECT_CLASS_LINK.CLASS_FID);
        public static final ForeignKey<SubjectClassLinkRecord, SubjectRecord> SUBJECT_CLASS_LINK__SUBJECT_CLASS_LINK_SUBJECT_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.SUBJECT_PKEY, SubjectClassLink.SUBJECT_CLASS_LINK, "subject_class_link__subject_class_link_subject_foreign_key", SubjectClassLink.SUBJECT_CLASS_LINK.SUBJECT_FID);
        public static final ForeignKey<TcsRecord, ClassRoomRecord> TCS__TCS_CLASS_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.CLASS_PKEY, Tcs.TCS, "tcs__tcs_class_foreign_key", Tcs.TCS.CLASS_FID);
        public static final ForeignKey<TcsRecord, SubjectRecord> TCS__TCS_SUBJECT_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.SUBJECT_PKEY, Tcs.TCS, "tcs__tcs_subject_foreign_key", Tcs.TCS.SUBJECT_FID);
        public static final ForeignKey<TcsRecord, TeacherRecord> TCS__TCS_TEACHER_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.TEACHER_PKEY, Tcs.TCS, "tcs__tcs_teacher_foreign_key", Tcs.TCS.TEACHER_FID);
        public static final ForeignKey<TeacherRecord, UsersRecord> TEACHER__FKSPQY2S83GVL6G8NT5AUBLS90K = Internal.createForeignKey(jooq.entities.Keys.USERS_PKEY, Teacher.TEACHER, "teacher__fkspqy2s83gvl6g8nt5aubls90k", Teacher.TEACHER.ID);
        public static final ForeignKey<TeacherRecord, ClassRoomRecord> TEACHER__CLASS_TEACHER_CLASS_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.CLASS_PKEY, Teacher.TEACHER, "teacher__class_teacher_class_foreign_key", Teacher.TEACHER.CLASS_FID);
        public static final ForeignKey<TeacherDepartmentLinkRecord, TeacherRecord> TEACHER_DEPARTMENT_LINK__TEACHER_DEPARTMENT_LINK_TEACHER_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.TEACHER_PKEY, TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK, "teacher_department_link__teacher_department_link_teacher_foreign_key", TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.TEACHER_FID);
        public static final ForeignKey<TeacherDepartmentLinkRecord, DepartmentRecord> TEACHER_DEPARTMENT_LINK__TEACHER_DEPARTMENT_LINK_DEPARTMENT_FOREIGN_KEY = Internal.createForeignKey(jooq.entities.Keys.DEPARTMENT_PKEY, TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK, "teacher_department_link__teacher_department_link_department_foreign_key", TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK.DEPARTMENT_FID);
    }
}
