/*
 * This file is generated by jOOQ.
 */
package jooq.entities;


import jooq.entities.tables.*;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.12"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -2114014232;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.admin</code>.
     */
    public final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>public.attendance</code>.
     */
    public final Attendance ATTENDANCE = Attendance.ATTENDANCE;

    /**
     * The table <code>public.class_room</code>.
     */
    public final ClassRoom CLASS_ROOM = ClassRoom.CLASS_ROOM;

    /**
     * The table <code>public.class_teacher_class_room_link</code>.
     */
    public final ClassTeacherClassRoomLink CLASS_TEACHER_CLASS_ROOM_LINK = ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK;

    /**
     * The table <code>public.course</code>.
     */
    public final Course COURSE = Course.COURSE;

    /**
     * The table <code>public.department</code>.
     */
    public final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>public.lecture</code>.
     */
    public final Lecture LECTURE = Lecture.LECTURE;

    /**
     * The table <code>public.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.student_subject_link</code>.
     */
    public final StudentSubjectLink STUDENT_SUBJECT_LINK = StudentSubjectLink.STUDENT_SUBJECT_LINK;

    /**
     * The table <code>public.subject</code>.
     */
    public final Subject SUBJECT = Subject.SUBJECT;

    /**
     * The table <code>public.subject_class_link</code>.
     */
    public final SubjectClassLink SUBJECT_CLASS_LINK = SubjectClassLink.SUBJECT_CLASS_LINK;

    /**
     * The table <code>public.tcs</code>.
     */
    public final Tcs TCS = Tcs.TCS;

    /**
     * The table <code>public.teacher</code>.
     */
    public final Teacher TEACHER = Teacher.TEACHER;

    /**
     * The table <code>public.teacher_department_link</code>.
     */
    public final TeacherDepartmentLink TEACHER_DEPARTMENT_LINK = TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
                Sequences.CLASS_ROOM_SEQUENCE,
                Sequences.COURSE_SEQUENCE,
                Sequences.DEPARTMENT_SEQUENCE,
                Sequences.SUBJECT_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Admin.ADMIN,
                Attendance.ATTENDANCE,
                ClassRoom.CLASS_ROOM,
                ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK,
                Course.COURSE,
                Department.DEPARTMENT,
                Lecture.LECTURE,
                Student.STUDENT,
                StudentSubjectLink.STUDENT_SUBJECT_LINK,
                Subject.SUBJECT,
                SubjectClassLink.SUBJECT_CLASS_LINK,
                Tcs.TCS,
                Teacher.TEACHER,
                TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK,
                Users.USERS);
    }
}
