/*
 * This file is generated by jOOQ.
 */
package jooq.entities;


import jooq.entities.routines.GetLectureId;
import jooq.entities.routines.RandomString;
import jooq.entities.routines.Test;
import org.jooq.Configuration;
import org.jooq.Field;

import javax.annotation.Generated;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.get_lecture_id</code>
     */
    public static String getLectureId(Configuration configuration) {
        GetLectureId f = new GetLectureId();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.get_lecture_id</code> as a field.
     */
    public static Field<String> getLectureId() {
        GetLectureId f = new GetLectureId();

        return f.asField();
    }

    /**
     * Call <code>public.random_string</code>
     */
    public static String randomString(Configuration configuration) {
        RandomString f = new RandomString();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.random_string</code> as a field.
     */
    public static Field<String> randomString() {
        RandomString f = new RandomString();

        return f.asField();
    }

    /**
     * Call <code>public.test</code>
     */
    public static void test(Configuration configuration) {
        Test p = new Test();

        p.execute(configuration);
    }
}
