/*
 * This file is generated by jOOQ.
 */
package jooq.entities;


import jooq.entities.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.12"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.admin</code>.
     */
    public static final Admin ADMIN = Admin.ADMIN;

    /**
     * The table <code>public.attendance</code>.
     */
    public static final Attendance ATTENDANCE = Attendance.ATTENDANCE;

    /**
     * The table <code>public.class_room</code>.
     */
    public static final ClassRoom CLASS_ROOM = ClassRoom.CLASS_ROOM;

    /**
     * The table <code>public.class_teacher_class_room_link</code>.
     */
    public static final ClassTeacherClassRoomLink CLASS_TEACHER_CLASS_ROOM_LINK = ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK;

    /**
     * The table <code>public.course</code>.
     */
    public static final Course COURSE = Course.COURSE;

    /**
     * The table <code>public.department</code>.
     */
    public static final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>public.lecture</code>.
     */
    public static final Lecture LECTURE = Lecture.LECTURE;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>public.student_subject_link</code>.
     */
    public static final StudentSubjectLink STUDENT_SUBJECT_LINK = StudentSubjectLink.STUDENT_SUBJECT_LINK;

    /**
     * The table <code>public.subject</code>.
     */
    public static final Subject SUBJECT = Subject.SUBJECT;

    /**
     * The table <code>public.subject_class_link</code>.
     */
    public static final SubjectClassLink SUBJECT_CLASS_LINK = SubjectClassLink.SUBJECT_CLASS_LINK;

    /**
     * The table <code>public.tcs</code>.
     */
    public static final Tcs TCS = Tcs.TCS;

    /**
     * The table <code>public.teacher</code>.
     */
    public static final Teacher TEACHER = Teacher.TEACHER;

    /**
     * The table <code>public.teacher_department_link</code>.
     */
    public static final TeacherDepartmentLink TEACHER_DEPARTMENT_LINK = TeacherDepartmentLink.TEACHER_DEPARTMENT_LINK;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
