/*
 * This file is generated by jOOQ.
 */
package jooq.entities.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.entities.Indexes;
import jooq.entities.Keys;
import jooq.entities.Public;
import jooq.entities.tables.records.SubjectRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subject extends TableImpl<SubjectRecord> {

    private static final long serialVersionUID = -1526136255;

    /**
     * The reference instance of <code>public.subject</code>
     */
    public static final Subject SUBJECT = new Subject();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubjectRecord> getRecordType() {
        return SubjectRecord.class;
    }

    /**
     * The column <code>public.subject.id</code>.
     */
    public final TableField<SubjectRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.subject.elective</code>.
     */
    public final TableField<SubjectRecord, Boolean> ELECTIVE = createField("elective", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.subject.name</code>.
     */
    public final TableField<SubjectRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * The column <code>public.subject.course_fid</code>.
     */
    public final TableField<SubjectRecord, Long> COURSE_FID = createField("course_fid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>public.subject</code> table reference
     */
    public Subject() {
        this(DSL.name("subject"), null);
    }

    /**
     * Create an aliased <code>public.subject</code> table reference
     */
    public Subject(String alias) {
        this(DSL.name(alias), SUBJECT);
    }

    /**
     * Create an aliased <code>public.subject</code> table reference
     */
    public Subject(Name alias) {
        this(alias, SUBJECT);
    }

    private Subject(Name alias, Table<SubjectRecord> aliased) {
        this(alias, aliased, null);
    }

    private Subject(Name alias, Table<SubjectRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Subject(Table<O> child, ForeignKey<O, SubjectRecord> key) {
        super(child, key, SUBJECT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SUBJECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SubjectRecord> getPrimaryKey() {
        return Keys.SUBJECT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SubjectRecord>> getKeys() {
        return Arrays.<UniqueKey<SubjectRecord>>asList(Keys.SUBJECT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Subject as(String alias) {
        return new Subject(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Subject as(Name alias) {
        return new Subject(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(String name) {
        return new Subject(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subject rename(Name name) {
        return new Subject(name, null);
    }
}
