/*
 * This file is generated by jOOQ.
 */
package jooq.entities.tables.records;


import java.util.UUID;

import javax.annotation.Generated;

import jooq.entities.tables.ClassTeacherClassRoomLink;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassTeacherClassRoomLinkRecord extends UpdatableRecordImpl<ClassTeacherClassRoomLinkRecord> implements Record2<Long, UUID> {

    private static final long serialVersionUID = 390458773;

    /**
     * Setter for <code>public.class_teacher_class_room_link.class_room_fid</code>.
     */
    public void setClassRoomFid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.class_teacher_class_room_link.class_room_fid</code>.
     */
    public Long getClassRoomFid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.class_teacher_class_room_link.class_teacher_fid</code>.
     */
    public void setClassTeacherFid(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.class_teacher_class_room_link.class_teacher_fid</code>.
     */
    public UUID getClassTeacherFid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK.CLASS_ROOM_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK.CLASS_TEACHER_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getClassRoomFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getClassTeacherFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getClassRoomFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getClassTeacherFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassTeacherClassRoomLinkRecord value1(Long value) {
        setClassRoomFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassTeacherClassRoomLinkRecord value2(UUID value) {
        setClassTeacherFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassTeacherClassRoomLinkRecord values(Long value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassTeacherClassRoomLinkRecord
     */
    public ClassTeacherClassRoomLinkRecord() {
        super(ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK);
    }

    /**
     * Create a detached, initialised ClassTeacherClassRoomLinkRecord
     */
    public ClassTeacherClassRoomLinkRecord(Long classRoomFid, UUID classTeacherFid) {
        super(ClassTeacherClassRoomLink.CLASS_TEACHER_CLASS_ROOM_LINK);

        set(0, classRoomFid);
        set(1, classTeacherFid);
    }
}
