/*
 * This file is generated by jOOQ.
 */
package jooq.entities.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import jooq.entities.tables.Lecture;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LectureRecord extends UpdatableRecordImpl<LectureRecord> implements Record5<String, Integer, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = 1112172632;

    /**
     * Setter for <code>public.lecture.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lecture.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.lecture.count</code>.
     */
    public void setCount(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lecture.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.lecture.date</code>.
     */
    public void setDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lecture.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.lecture.ended</code>.
     */
    public void setEnded(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lecture.ended</code>.
     */
    public Boolean getEnded() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.lecture.tcs_fid</code>.
     */
    public void setTcsFid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lecture.tcs_fid</code>.
     */
    public Long getTcsFid() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Integer, Timestamp, Boolean, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Integer, Timestamp, Boolean, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Lecture.LECTURE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Lecture.LECTURE.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Lecture.LECTURE.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Lecture.LECTURE.ENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Lecture.LECTURE.TCS_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getTcsFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getTcsFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value2(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value3(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value4(Boolean value) {
        setEnded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value5(Long value) {
        setTcsFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord values(String value1, Integer value2, Timestamp value3, Boolean value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LectureRecord
     */
    public LectureRecord() {
        super(Lecture.LECTURE);
    }

    /**
     * Create a detached, initialised LectureRecord
     */
    public LectureRecord(String id, Integer count, Timestamp date, Boolean ended, Long tcsFid) {
        super(Lecture.LECTURE);

        set(0, id);
        set(1, count);
        set(2, date);
        set(3, ended);
        set(4, tcsFid);
    }
}
