/*
 * This file is generated by jOOQ.
 */
package jooq.entities.tables.records;


import jooq.entities.tables.Lecture;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.12"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class LectureRecord extends UpdatableRecordImpl<LectureRecord> implements Record6<String, Integer, Timestamp, Boolean, Long, Long> {

    private static final long serialVersionUID = -873931081;

    /**
     * Setter for <code>public.lecture.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lecture.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.lecture.count</code>.
     */
    public void setCount(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lecture.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.lecture.date</code>.
     */
    public void setDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lecture.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.lecture.ended</code>.
     */
    public void setEnded(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lecture.ended</code>.
     */
    public Boolean getEnded() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.lecture.tcs_class_room_fid</code>.
     */
    public void setTcsClassRoomFid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lecture.tcs_class_room_fid</code>.
     */
    public Long getTcsClassRoomFid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.lecture.tcs_subject_fid</code>.
     */
    public void setTcsSubjectFid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lecture.tcs_subject_fid</code>.
     */
    public Long getTcsSubjectFid() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Integer, Timestamp, Boolean, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Integer, Timestamp, Boolean, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Lecture.LECTURE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Lecture.LECTURE.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Lecture.LECTURE.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Lecture.LECTURE.ENDED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Lecture.LECTURE.TCS_CLASS_ROOM_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Lecture.LECTURE.TCS_SUBJECT_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getTcsClassRoomFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getTcsSubjectFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getEnded();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getTcsClassRoomFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getTcsSubjectFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value2(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value3(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value4(Boolean value) {
        setEnded(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value5(Long value) {
        setTcsClassRoomFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord value6(Long value) {
        setTcsSubjectFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LectureRecord values(String value1, Integer value2, Timestamp value3, Boolean value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LectureRecord
     */
    public LectureRecord() {
        super(Lecture.LECTURE);
    }

    /**
     * Create a detached, initialised LectureRecord
     */
    public LectureRecord(String id, Integer count, Timestamp date, Boolean ended, Long tcsClassRoomFid, Long tcsSubjectFid) {
        super(Lecture.LECTURE);

        set(0, id);
        set(1, count);
        set(2, date);
        set(3, ended);
        set(4, tcsClassRoomFid);
        set(5, tcsSubjectFid);
    }
}
