/*
 * This file is generated by jOOQ.
 */
package jooq.entities.tables.records;


import jooq.entities.tables.Tcs;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TcsRecord extends UpdatableRecordImpl<TcsRecord> implements Record4<Long, Long, Long, UUID> {

    private static final long serialVersionUID = 872439875;

    /**
     * Setter for <code>public.tcs.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tcs.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tcs.class_fid</code>.
     */
    public void setClassFid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tcs.class_fid</code>.
     */
    public Long getClassFid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.tcs.subject_fid</code>.
     */
    public void setSubjectFid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tcs.subject_fid</code>.
     */
    public Long getSubjectFid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.tcs.teacher_fid</code>.
     */
    public void setTeacherFid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tcs.teacher_fid</code>.
     */
    public UUID getTeacherFid() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, UUID> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Long, UUID> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Tcs.TCS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Tcs.TCS.CLASS_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Tcs.TCS.SUBJECT_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return Tcs.TCS.TEACHER_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getClassFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getSubjectFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component4() {
        return getTeacherFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getClassFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getSubjectFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getTeacherFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord value2(Long value) {
        setClassFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord value3(Long value) {
        setSubjectFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord value4(UUID value) {
        setTeacherFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord values(Long value1, Long value2, Long value3, UUID value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TcsRecord
     */
    public TcsRecord() {
        super(Tcs.TCS);
    }

    /**
     * Create a detached, initialised TcsRecord
     */
    public TcsRecord(Long id, Long classFid, Long subjectFid, UUID teacherFid) {
        super(Tcs.TCS);

        set(0, id);
        set(1, classFid);
        set(2, subjectFid);
        set(3, teacherFid);
    }
}
