/*
 * This file is generated by jOOQ.
 */
package jooq.entities.tables.records;


import jooq.entities.tables.Tcs;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.11.12"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class TcsRecord extends UpdatableRecordImpl<TcsRecord> implements Record3<Long, Long, UUID> {

    private static final long serialVersionUID = 1111346720;

    /**
     * Setter for <code>public.tcs.class_room_fid</code>.
     */
    public void setClassRoomFid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tcs.class_room_fid</code>.
     */
    public Long getClassRoomFid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tcs.subject_fid</code>.
     */
    public void setSubjectFid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tcs.subject_fid</code>.
     */
    public Long getSubjectFid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.tcs.teacher_fid</code>.
     */
    public void setTeacherFid(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tcs.teacher_fid</code>.
     */
    public UUID getTeacherFid() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, UUID> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, UUID> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Tcs.TCS.CLASS_ROOM_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Tcs.TCS.SUBJECT_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field3() {
        return Tcs.TCS.TEACHER_FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getClassRoomFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getSubjectFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component3() {
        return getTeacherFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getClassRoomFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSubjectFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value3() {
        return getTeacherFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord value1(Long value) {
        setClassRoomFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord value2(Long value) {
        setSubjectFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord value3(UUID value) {
        setTeacherFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TcsRecord values(Long value1, Long value2, UUID value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TcsRecord
     */
    public TcsRecord() {
        super(Tcs.TCS);
    }

    /**
     * Create a detached, initialised TcsRecord
     */
    public TcsRecord(Long classRoomFid, Long subjectFid, UUID teacherFid) {
        super(Tcs.TCS);

        set(0, classRoomFid);
        set(1, subjectFid);
        set(2, teacherFid);
    }
}
