/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postback;

import entities.Login;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.hibernate.Session;
import utility.Utils;

/**
 *
 * @author sukhvir
 */
@WebServlet(urlPatterns = "/resetpasswordpost")
public class ResetPasswordPost extends HttpServlet {
    
    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String username = req.getParameter("username");
        String password = req.getParameter("password");
        Session session = Utils.openSession();
        session.beginTransaction();
        Login login = (Login) session.get(Login.class, username);
        login.setPassword(password);
        login.setUsed(true);
        session.update(login);
        session.getTransaction().commit();
        session.close();
        String body = "this is an autogenerated mail. Please don't reply or send mail to this address. Your password was changed on " + new Date();
        Utils.sendMail(login.getEmail(), "Password changed", body);
        resp.sendRedirect("login");
    }
    
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        PrintWriter out = resp.getWriter();
        out.print("error");
        out.close();
    }
    
}
